[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
undefined_temporary = "G6k7MrFMpQtLDDLzoJf2F6gza9na31KnVwjbUsxGQEPJ"

[programs.Devnet]
undefined_temporary = "G6k7MrFMpQtLDDLzoJf2F6gza9na31KnVwjbUsxGQEPJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nicolasbeaudouin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
